### PR TITLE
fix: update Migaloo doc link

### PR DESCRIPTION
**Pull request by cryptassic**
## Description and Motivation

Old link points to chinese unfinished website

Current link points to this:
image

---
## Checklist:

- [ x ] I have read [Migaloo's contribution guidelines](https://github.com/White-Whale-Defi-Platform/migaloo-core/blob/main/CONTRIBUTING.md).
- [ x ] My pull request has a sound title and description (not something vague like `Update index.md`)
- [ x ] All existing and new tests are passing.
- [ x ] I updated/added relevant documentation.
- [ x ] The code is formatted properly `cargo fmt --all --`.
- [ x ] Clippy doesn't report any issues `cargo clippy -- -D warnings`.
- [ x ] I have regenerated the schemas if needed `cargo schema`.

### CODE REVIEW

**Comment by kerber0x** [comment]
Hi and thanks for reporting this issue! We got something similar in the past and fixed it but i guess we missed something, where did you find this link exactly?

**Comment by cryptassic** [comment]
I was going through docs here: https://github.com/White-Whale-Defi-Platform/white-whale-core/tree/main/contracts/liquidity_hub/pool-network/terraswap_factory

**Comment by kerber0x** [comment]
> I was going through docs here: https://github.com/White-Whale-Defi-Platform/white-whale-core/tree/main/contracts/liquidity_hub/pool-network/terraswap_factory

Cool, yes we definitely missed that one. We updated the docs link for the white whale protocol, it is https://docs.whitewhale.money/white-whale now.

Thanks for reporting this, will fix soon :+1:

**Review by kerber0x — CHANGES_REQUESTED** [review]
docs.migaloo.zone refers to the migaloo chain documentation. For white whale smart contracts, it is https://docs.whitewhale.money/.

For the pool factory specifically, it is https://docs.whitewhale.money/white-whale/liquidity-hub/overview-1/terraswap-factory

**Pull request closed without merging**
