### PR TITLE
Generate schema through workspace build script

### PR DESCRIPTION
**Pull request by kaimen-sano**
## Description and Motivation

We currently generate schemas by having a binary `schema.rs` on each contract which will use the `cosmwasm_schema` API to write a schema.

While this works, it requires us to maintain the binary for each contract. This is tedious (extra files per contract, including a `.cargo` alias definition), and also requires us to correctly use the `cosmwasm_schema` per contract. Additionally, we were getting Cargo binary name collisions:
```
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
```

This PR aims to standardize the process of creating a schema for a contract by moving the logic to a new [`xtask`](https://github.com/matklad/cargo-xtask): `generate_schemas`. This task will generate all the schema files for the entire workspace at once.

This is similar work to the previous `just schemas` (which was broken), however we now get the benefit of being able to remove the binary from each contract. This could potentially speed up compile times.

This PR also moves the schema PR workflow check to a new workflow file, and aims to add a comment to the PR if the schemas failed.

---

## Checklist:

- [X] I have read [Migaloo's contribution guidelines](https://github.com/White-Whale-Defi-Platform/migaloo-core/blob/main/docs/CONTRIBUTING.md).
- [X] My pull request has a sound title and description (not something vague like `Update index.md`)
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation.
- [X] The code is formatted properly `cargo fmt --all --`.
- [X] Clippy doesn't report any issues `cargo clippy -- -D warnings`.
- [X] I have regenerated the schemas if needed with `just schemas`.

### CODE REVIEW

**Comment by kaimen-sano** [comment]
Elected to exclude `xtask` from Tarpaulin here. It is not a critical piece of software for us to test.

**Comment by kaimen-sano** [comment]
Good to review, finally :)

**Comment by kaimen-sano** [comment]
> LGTM great work never heard of xtask until now but looks like its even used by Cargo 🤯

It was a great find to run scripts for the workspace that need access to our Rust interfaces. I was also not aware of how widespread the pattern is in the Rust ecosystem, but it certainly looks like a nice complement to `just` for our case.

**Comment by kerber0x** [comment]
:shipit: @kaimen-sano

**Pull request merged**
